---
- name: Testing Roles and Collections
  hosts: localhost
  become: false
  gather_facts: false
  roles:  
    #### Simple roles and galaxy collection roles are declared in your main.yml file differently as seen below
    ## web is from "ansible-galaxy role init web"
    ## linuxist is from "ansible-galaxy collection init linuxist.my_collection" and then inside of it I ran "ansible-galaxy role init chrony"
    - web   # this is a simpel anxible-galaxy role named 'web' declared to use the role
    - linuxist.my_collection.chrony  ##### this is out new ansible-galaxy collection role declared to use which we created earlier

  tasks:
    - name: Display Data
      ignore_errors: true
      ansible.builtin.debug:
        #msg: "{{ 'Hello Ansible' | upper_case }}"
        msg: "{{ 'Hello Ansible' | linuxist.my_collection.upper_case }}"

    - name: Create user
      become: true
      ansible.builtin.user:
        name: user2
        state: present
        password: "{{ 'letmein2' | password_hash('sha512') }}"
        update_password: on_create

    - name: Add PUPPET repository
      become: true
      ansible.builtin.yum_repository:
        name: puppet
        description: Official Puppet Repository
        baseurl: https://yum.puppet.com/puppet8/el/9/$basearch
        gpgkey: https://yum.puppet.com/RPM-GPG-KEY-puppet
        state: present
