---
- name: Testing Roles and Collections
  hosts: localhost
  become: false
  gather_facts: false
  roles:  
    #### Simple roles and galaxy collection roles are declared in your main.yml file differently as seen below
    ## web is from "ansible-galaxy role init web"
    ## linuxist is from "ansible-galaxy collection init linuxist.my_collection" and then inside of it I ran "ansible-galaxy role init chrony"
    - web   # this is a simpel anxible-galaxy role named 'web' declared to use the role
    - linuxist.my_collection.chrony  ##### this is out new ansible-galaxy collection role declared to use which we created earlier
