---
- name: Install HTTPD
  become: true
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Enable the HTTPD service
  become: true
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
