---
- name: Test error Handling
  hosts: localhost
  gather_facts: false
  become: true
  ignore_errors: true

  tasks:
    - name: Install Apache (Ubuntu)
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present          
    - name: Install Apache (RHEL)
      ansible.builtin.dnf:
        name: httpd
        update_cache: true
        state: present
